---
name: Code Quality Checks (Python 3.10)

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry update
      - name: Unit & Coverage test with pytest
        run: poetry run pytest
      - name: Check style with pylint
        run: poetry run pylint pycommons/ tests/
      - name: Check format with black
        run: poetry run black --check pycommons/ tests/
      - name: Check type hinting with mypy
        run: poetry run mypy --namespace-packages -p pycommons.{{project_name}} --strict --config-file=mypy.ini

